trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    checkLatest: true
  displayName: "Install NodeJs"
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'JMDBProvider/'
  displayName: "Install Npm Packages"
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Release'
    clean: true
  displayName: "Build Project"
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
    workingDir: 'JMDBProvider/'
  displayName: "Run Tests"
- task: CopyFiles@2
  inputs:
    SourceFolder: 'JMDBProvider/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/JMDBProvider/'
  displayName: "Copy Files to Artifacts Folder"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: "Publish Artifacts"
